version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "4p5ma6io-responses:1:1,4p5ma6io-multiply-request:1:1,4p5ma6io-test-ping:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
