version: 1.0.{build}
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    nuget restore src\SlimMessageBus.sln

    build\do_package.ps1
test:
  categories:
    except:
    - Integration
artifacts:
- path: dist\SlimMessageBus.*.nupkg
  name: SlimMessageBus
deploy: off
notifications:
- provider: Email
  to:
  - maruszaktomasz@gmail.com
  subject: '[Build] SlimMessageBus'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true